// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: grpc.proto

package google_golang_org

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           string                 `protobuf:"bytes,1,opt,name=Mid,proto3" json:"Mid,omitempty"`
	Jwt           string                 `protobuf:"bytes,2,opt,name=Jwt,proto3" json:"Jwt,omitempty"`
	Sid           string                 `protobuf:"bytes,3,opt,name=Sid,proto3" json:"Sid,omitempty"`
	Ver           *string                `protobuf:"bytes,4,opt,name=Ver,proto3,oneof" json:"Ver,omitempty"`
	Typ           *string                `protobuf:"bytes,5,opt,name=Typ,proto3,oneof" json:"Typ,omitempty"`
	Code          *int32                 `protobuf:"varint,6,opt,name=Code,proto3,oneof" json:"Code,omitempty"`
	Reason        *string                `protobuf:"bytes,7,opt,name=Reason,proto3,oneof" json:"Reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

func (x *Header) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

func (x *Header) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *Header) GetVer() string {
	if x != nil && x.Ver != nil {
		return *x.Ver
	}
	return ""
}

func (x *Header) GetTyp() string {
	if x != nil && x.Typ != nil {
		return *x.Typ
	}
	return ""
}

func (x *Header) GetCode() int32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *Header) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Met           string                 `protobuf:"bytes,1,opt,name=Met,proto3" json:"Met,omitempty"`
	MsgH          *Header                `protobuf:"bytes,2,opt,name=MsgH,proto3" json:"MsgH,omitempty"`
	ReqParams     []string               `protobuf:"bytes,3,rep,name=ReqParams,proto3" json:"ReqParams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetMet() string {
	if x != nil {
		return x.Met
	}
	return ""
}

func (x *Request) GetMsgH() *Header {
	if x != nil {
		return x.MsgH
	}
	return nil
}

func (x *Request) GetReqParams() []string {
	if x != nil {
		return x.ReqParams
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgH          *Header                `protobuf:"bytes,1,opt,name=MsgH,proto3" json:"MsgH,omitempty"`
	ResValues     []string               `protobuf:"bytes,2,rep,name=ResValues,proto3" json:"ResValues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetMsgH() *Header {
	if x != nil {
		return x.MsgH
	}
	return nil
}

func (x *Response) GetResValues() []string {
	if x != nil {
		return x.ResValues
	}
	return nil
}

type CData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Close         *bool                  `protobuf:"varint,1,opt,name=Close,proto3,oneof" json:"Close,omitempty"`
	Req           *Request               `protobuf:"bytes,2,opt,name=Req,proto3,oneof" json:"Req,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=Data,proto3,oneof" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CData) Reset() {
	*x = CData{}
	mi := &file_grpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CData) ProtoMessage() {}

func (x *CData) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CData.ProtoReflect.Descriptor instead.
func (*CData) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *CData) GetClose() bool {
	if x != nil && x.Close != nil {
		return *x.Close
	}
	return false
}

func (x *CData) GetReq() *Request {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *CData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_grpc_proto protoreflect.FileDescriptor

const file_grpc_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"grpc.proto\x12\x04grpc\"\xc6\x01\n" +
	"\x06Header\x12\x10\n" +
	"\x03Mid\x18\x01 \x01(\tR\x03Mid\x12\x10\n" +
	"\x03Jwt\x18\x02 \x01(\tR\x03Jwt\x12\x10\n" +
	"\x03Sid\x18\x03 \x01(\tR\x03Sid\x12\x15\n" +
	"\x03Ver\x18\x04 \x01(\tH\x00R\x03Ver\x88\x01\x01\x12\x15\n" +
	"\x03Typ\x18\x05 \x01(\tH\x01R\x03Typ\x88\x01\x01\x12\x17\n" +
	"\x04Code\x18\x06 \x01(\x05H\x02R\x04Code\x88\x01\x01\x12\x1b\n" +
	"\x06Reason\x18\a \x01(\tH\x03R\x06Reason\x88\x01\x01B\x06\n" +
	"\x04_VerB\x06\n" +
	"\x04_TypB\a\n" +
	"\x05_CodeB\t\n" +
	"\a_Reason\"[\n" +
	"\aRequest\x12\x10\n" +
	"\x03Met\x18\x01 \x01(\tR\x03Met\x12 \n" +
	"\x04MsgH\x18\x02 \x01(\v2\f.grpc.HeaderR\x04MsgH\x12\x1c\n" +
	"\tReqParams\x18\x03 \x03(\tR\tReqParams\"J\n" +
	"\bResponse\x12 \n" +
	"\x04MsgH\x18\x01 \x01(\v2\f.grpc.HeaderR\x04MsgH\x12\x1c\n" +
	"\tResValues\x18\x02 \x03(\tR\tResValues\"|\n" +
	"\x05CData\x12\x19\n" +
	"\x05Close\x18\x01 \x01(\bH\x00R\x05Close\x88\x01\x01\x12$\n" +
	"\x03Req\x18\x02 \x01(\v2\r.grpc.RequestH\x01R\x03Req\x88\x01\x01\x12\x17\n" +
	"\x04Data\x18\x03 \x01(\fH\x02R\x04Data\x88\x01\x01B\b\n" +
	"\x06_CloseB\x06\n" +
	"\x04_ReqB\a\n" +
	"\x05_Data2\\\n" +
	"\x04Grpc\x12(\n" +
	"\x05Route\x12\r.grpc.Request\x1a\x0e.grpc.Response\"\x00\x12*\n" +
	"\bRWStream\x12\v.grpc.CData\x1a\v.grpc.CData\"\x00(\x010\x01B\x13Z\x11google.golang.orgb\x06proto3"

var (
	file_grpc_proto_rawDescOnce sync.Once
	file_grpc_proto_rawDescData []byte
)

func file_grpc_proto_rawDescGZIP() []byte {
	file_grpc_proto_rawDescOnce.Do(func() {
		file_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_proto_rawDesc), len(file_grpc_proto_rawDesc)))
	})
	return file_grpc_proto_rawDescData
}

var file_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_proto_goTypes = []any{
	(*Header)(nil),   // 0: grpc.Header
	(*Request)(nil),  // 1: grpc.Request
	(*Response)(nil), // 2: grpc.Response
	(*CData)(nil),    // 3: grpc.CData
}
var file_grpc_proto_depIdxs = []int32{
	0, // 0: grpc.Request.MsgH:type_name -> grpc.Header
	0, // 1: grpc.Response.MsgH:type_name -> grpc.Header
	1, // 2: grpc.CData.Req:type_name -> grpc.Request
	1, // 3: grpc.Grpc.Route:input_type -> grpc.Request
	3, // 4: grpc.Grpc.RWStream:input_type -> grpc.CData
	2, // 5: grpc.Grpc.Route:output_type -> grpc.Response
	3, // 6: grpc.Grpc.RWStream:output_type -> grpc.CData
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_grpc_proto_init() }
func file_grpc_proto_init() {
	if File_grpc_proto != nil {
		return
	}
	file_grpc_proto_msgTypes[0].OneofWrappers = []any{}
	file_grpc_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_proto_rawDesc), len(file_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_goTypes,
		DependencyIndexes: file_grpc_proto_depIdxs,
		MessageInfos:      file_grpc_proto_msgTypes,
	}.Build()
	File_grpc_proto = out.File
	file_grpc_proto_goTypes = nil
	file_grpc_proto_depIdxs = nil
}
